export const serializeProfile = (user) => ({
  id: user.id,
  full_name: user.fullName,
  email: user.email,
  phone: user.phone ?? '',
  avatar_url: user.avatar?.url ?? null,
  avatar_public_id: user.avatar?.publicId ?? null,
  role: user.role,
  created_at: user.createdAt.toISOString(),
  updated_at: user.updatedAt.toISOString(),
});

export const serializeProduct = (product) => ({
  id: product.id,
  name: product.name,
  slug: product.slug,
  category: product.category,
  price: product.price,
  ...(product.discountPrice != null ? { discountPrice: product.discountPrice } : {}),
  images: product.images.map((image) => image.url),
  imageAssets: product.images.map((image) => ({ url: image.url, publicId: image.publicId })),
  stock: product.stock,
  stockStatus: product.stockStatus,
  status: product.status,
  featured: product.featured,
  size: product.size,
  description: product.description,
  shortDescription: product.shortDescription,
  benefits: product.benefits,
  ingredients: product.ingredients,
  howToUse: product.howToUse,
  hairTypes: product.hairTypes,
  rating: product.rating,
  reviewCount: product.reviewCount,
  sku: product.sku ?? '',
  createdAt: product.createdAt.toISOString(),
  updatedAt: product.updatedAt.toISOString(),
});

export const serializeService = (service) => ({
  id: service.id,
  name: service.name,
  slug: service.slug,
  price: service.price,
  duration: service.duration,
  description: service.description,
  benefits: service.benefits,
  image: service.image?.url ?? '',
  imageAsset: service.image ? { url: service.image.url, publicId: service.image.publicId } : null,
  available: service.available,
  deliverable: service.deliverable,
  popular: service.popular,
});

export const serializeOrder = (order) => ({
  id: order.id,
  orderNumber: order.orderNumber,
  customerInfo: order.customerInfo,
  items: order.items.map((item) => ({
    productId: item.productId,
    productName: item.productName,
    size: item.size,
    quantity: item.quantity,
    price: item.price,
    image: item.image,
  })),
  subtotal: order.subtotal,
  totalAmount: order.totalAmount,
  status: order.status,
  createdAt: order.createdAt.toISOString(),
});
